name: Build and deploy ASP.Net Core app to Azure Web App - GameStoreRahul

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3  # Using @v3 for latest stable version

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3  # Using @v3 for latest stable version
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore GameStore.FrontEnd/GameStore.FrontEnd.csproj

      - name: Build with dotnet
        run: dotnet build GameStore.FrontEnd/GameStore.FrontEnd.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish GameStore.FrontEnd/GameStore.FrontEnd.csproj --configuration Release --output myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app
          path: myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GameStoreRahul'
          package: myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB67B05A579C421DA8E121F734AA2942 }}
